### ISSUE TITLE
Log Updates

### ISSUE THREAD

**Issue by jaburgeson** [jmaferreira/homebridge-garage-door-shelly1#2]
First off, thank you for adapting this plugin for the Shelly1.  It is working great!

Curious, is there a way to only have the log update when there is a status change with the door instead of on the polling interval?

Apologies ahead of time if I am missing something.

Thanks!

**Comment by jmaferreira** [comment]
Hi,

Thank you for your interest. I kept the warning on the log file mostly for debugging reasons. I promise to remove it on the next release as it is no longer necessary.

Cheers.
