### ISSUE TITLE
Fechar Portão - Duplo Clique

### ISSUE THREAD

**Issue by JKSProds** [jmaferreira/homebridge-garage-door-shelly1#6]
Olá,

Tenho usado o teu plugin e desde já muito obrigado. Está excelente. No entanto existe uma coisa que gostaria que estivesse implementado. Para fechar o portão deveria haver uma opção para ativar duplo clique. Senão no meu portão ele apenas para!

Obrigado

**Comment by jmaferreira** [comment]
Penso que esse comportamento não é possível. O shelly apenas envia um sinal OFF-ON-OFF (1 seg) para a controladora do portão. O comportamento do portão é controlado pela placa do portão. 

Penso que há placas que permitem alterar o comportamento do motor quando recebe um sinal enquanto o portão está a abrir, mas isso deve variar de modelo para modelo.
